package com.softdesign.devintensive.data.storage.models;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "LIKES".
 */
public class LikesDao extends AbstractDao<Likes, Long> {

    public static final String TABLENAME = "LIKES";

    /**
     * Properties of entity Likes.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property LikesBy = new Property(1, String.class, "LikesBy", false, "LIKES_BY");
        public final static Property UserRemoteId = new Property(2, String.class, "userRemoteId", false, "USER_REMOTE_ID");
    }

    ;

    private DaoSession daoSession;


    public LikesDao(DaoConfig config) {
        super(config);
    }

    public LikesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "\"LIKES\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LIKES_BY\" TEXT," + // 1: LikesBy
                "\"USER_REMOTE_ID\" TEXT);"); // 2: userRemoteId
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LIKES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Likes entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String LikesBy = entity.getLikesBy();
        if (LikesBy != null) {
            stmt.bindString(2, LikesBy);
        }

        String userRemoteId = entity.getUserRemoteId();
        if (userRemoteId != null) {
            stmt.bindString(3, userRemoteId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Likes entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }

        String LikesBy = entity.getLikesBy();
        if (LikesBy != null) {
            stmt.bindString(2, LikesBy);
        }

        String userRemoteId = entity.getUserRemoteId();
        if (userRemoteId != null) {
            stmt.bindString(3, userRemoteId);
        }
    }

    @Override
    protected final void attachEntity(Likes entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public Likes readEntity(Cursor cursor, int offset) {
        Likes entity = new Likes( //
                cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // LikesBy
                cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // userRemoteId
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Likes entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setLikesBy(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserRemoteId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
    }

    @Override
    protected final Long updateKeyAfterInsert(Likes entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(Likes entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }

}
